<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-31 01:05
=======
# Generated by Django 5.1.7 on 2025-03-31 00:21
>>>>>>> 71f3d70f859bf005a6a612ab8cb43a872c3acfcd

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0003_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_ingredients',
            field=models.ManyToManyField(blank=True, related_name='disliked_by_users', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_cuisines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('chef', 'Chef'), ('amateur', 'Amateur'), ('blogueur', 'Blogueur')], max_length=20),
        ),
    ]
