# Generated by Django 5.1.7 on 2025-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_likes'),
        ('users', '0004_user_disliked_ingredients_user_liked_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='recipes.recipe'),
        ),
    ]
