# Generated by Django 4.2.20 on 2025-04-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('chef', 'Chef'), ('amateur', 'Amateur'), ('blogueur', 'Blogueur')], max_length=20),
        ),
    ]
