# Generated by Django 4.2.20 on 2025-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('chef', 'Chef'), ('amateur', 'Amateur'), ('blogueur', 'Blogueur')], max_length=20),
        ),
    ]
