# Generated by Django 4.2.20 on 2025-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('blogueur', 'Blogueur')], default='blogueur', max_length=20),
        ),
    ]
