# Generated by Django 4.2.20 on 2025-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chef_application_status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('blogueur', 'Blogueur'), ('chef', 'Chef')], default='blogueur', max_length=20),
        ),
    ]
