# Generated by Django 4.2.20 on 2025-04-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='can_approve_recipes',
            new_name='can_approve_chefs',
        ),
    ]
